// 命名：模块名+功能
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_SYSTEM_INFO = 'GET_SYSTEM_INFO';

export const CHANGE_STORELIST_NAV = 'CHANGE_STORELIST_NAV';
export const CHANGE_STORELIST_SHOWSPINNER = 'CHANGE_STORELIST_SHOWSPINNER';
export const GET_STORELIST_SPINNERS = 'GET_STORELIST_SPINNERS';

export const GET_STORE_LOCATION = 'GET_STORE_LOCATION';
export const SET_STORE_GOODSMORE = 'SET_STORE_GOODSMORE';
export const SET_STORE_PHOTOSCAN = 'SET_STORE_PHOTOSCAN'; // 图片预览
export const STORE_OPENLOCATION = 'STORE_OPENLOCATION';
